#! /bin/bash

### Set MongoDB's development settings only for Linux
if [ "$(uname)" != "Darwin" ]; then
    # BEGIN LC_ALL=C
    export LC_ALL="C"
    # END LC_ALL=C
    # BEGIN ULIMITS BLOCK
    ulimit -v unlimited
    ulimit -n 64000
    ulimit -u 64000
    ulimit -l 256000
    # END ULIMITS BLOCK
    # BEGIN ULIMITS BLOCK WT
    ulimit -c unlimited
    # END ULIMITS BLOCK WT
fi

# Export HISTFILE so that bash scripts will be able to read it
export HISTFILE

# Initialize const variables
WORKSPACE_MONGODB_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

### Set common Linux settings
. $(dirname $WORKSPACE_MONGODB_DIR)/common/bashrc_lnx

### Source bash scripts
BASHRC_D_PATH="$WORKSPACE_MONGODB_DIR/scripts/bashrc.d"
for file in $(find $BASHRC_D_PATH -type f); do
    source $file
done

source $HOME/.fss/bin/fss.sh

### Required by mtools
source $HOME/.asdf/asdf.sh
source $HOME/.asdf/completions/asdf.bash

export PATH=$WORKSPACE_MONGODB_DIR/scripts/bin:${PATH}

### Export development dependency binaries
[[ -d /opt/nodejs/node-v8.11.3-linux-x64 ]] && export PATH=/opt/nodejs/node-v8.11.3-linux-x64/bin:${PATH}
export NINJA_STATUS='[%f/%t (%p) %es] '
#[[ -d $HOME/.cargo ]] && . "$HOME/.cargo/env"

### Mongo aliases
alias gbs="git branch --list 'suhu*'"
alias s="mon_repoSummary.sh"
alias sa="mon_allReposSummary.sh"
alias t="tail -f tests.log"
alias tf="tail -f tests.log | grep -e 'failed to load' -e 'Invariant' -e 'Writing fatal' -e 'Tripwire assertion' -e 'SSS'"
alias ltf="mrlog tests.log | l -Sn +/'failed to load' +uujjj"

alias ss_repeatTest="$WORKSPACE_MONGODB_DIR/tools/testing/repeatTestUntilFailure.sh"
alias ss_merge_and_sort_logs="grep -r ^ . | sed -E \"s/^([^:]*)\:{([^,]*)/{\2, \\\"n\\\"\:\1/g\" | sort"
alias compile_v40='./buildscripts/scons.py --variables-files=etc/scons/mongodbtoolchain_stable_clang.vars --opt=on --dbg=on ICECC=icecc all'
alias compile_v50='./buildscripts/scons.py --variables-files=etc/scons/mongodbtoolchain_stable_clang.vars --opt=on --dbg=on --link-model=dynamic --ninja generate-ninja ICECC=icecc CCACHE=ccache'

alias sm="evergreen notify slack -t '@silvia.surroca@mongodb.com' -m "

# BEGIN Source server_bashrc.sh
#source /home/ubuntu/mongodb-mongo-master/server-workflow-tool/server_bashrc.sh
# END Source server_bashrc.sh
