#! /bin/bash

### Add Homebrew binary directory to path
export PATH=/opt/homebrew/bin:${PATH}

### Set Homebrew bash completion
[[ -r /usr/local/etc/profile.d/bash_completion.sh ]] && . /usr/local/etc/profile.d/bash_completion.sh

# Export Terminal main color (used by TMUX and Oh My Posh)
export TERM_MAIN_COLOR="#50b9ff"

# Setting PATH for Python 3.11
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.11/bin:${PATH}"
export PATH

# Setting PATH for Python 2.7
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
export PATH

# Setting PATH for llvm binaries
export PATH="/opt/homebrew/opt/llvm/bin:$PATH"

# Setting PATH for mrlog
export PATH="$HOME/projects/mrlog/target/release:${PATH}"

# Task-spooler alias to get parity between Linux and Macos
alias tsp=ts

### Set common and MongoDB settings
. ~/.config/workspace/mongodb/bashrc_lnx

. "$HOME/.cargo/env"
