#! /bin/bash

### Add Homebrew binary directory to path
export PATH=/opt/homebrew/bin:${PATH}

### Set Homebrew bash completion
[[ -r /usr/local/etc/profile.d/bash_completion.sh ]] && . /usr/local/etc/profile.d/bash_completion.sh

### Set common and MongoDB settings
. ~/.config/workspace/mongodb/bashrc_lnx

# Export Terminal main color (used by TMUX and Oh My Posh)
export TERM_MAIN_COLOR="#50b9ff"

# Export paths
export PATH=~/Library/Python/3.9/bin:${PATH}
