#! /bin/bash

# Initialize the following variables
SCRIPT_DIR=$(dirname "$(realpath "${BASH_SOURCE[0]}")")

### Add Homebrew binary directory to path
export PATH=/opt/homebrew/bin:${PATH}

### Set Homebrew bash completion
if type brew &>/dev/null
then
  HOMEBREW_PREFIX="$(brew --prefix)"
  if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]
  then
    source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
  else
    for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*
    do
      [[ -r "${COMPLETION}" ]] && source "${COMPLETION}"
    done
  fi
fi

# Setting PATH for mrlog
export PATH=${HOME}/.mrlog/target/release:${PATH}

### Set Oh My Posh config file
export POSH_CONFIG_FILE=${SCRIPT_DIR}/oh-my-posh/custom_mac.omp.json

# Export Terminal main color (used by TMUX and Oh My Posh)
export TERM_MAIN_COLOR="#50b9ff"

### Source common and MongoDB settings
. $SCRIPT_DIR/bashrc_lnx


