let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()
Plug 'yunlingz/equinusocio-material.vim'
Plug 'rhysd/vim-clang-format'
"Plug 'https://github.com/ycm-core/YouCompleteMe', { 'dir': '~/.vim/plugged/YouCompleteMe', 'do': 'python3 install.py --clang-completer' }
if v:version >= 800
    Plug 'https://github.com/dense-analysis/ale.git', { 'tag': 'v2.6.0' }
endif

Plug 'https://github.com/lyuts/vim-rtags'

Plug 'https://github.com/junegunn/fzf', { 'tag': '0.20.0', 'dir': '~/.fzf', 'do': './install --all --no-update-rc' }
Plug 'https://github.com/junegunn/fzf.vim'

call plug#end()

set termguicolors
colorscheme equinusocio_material

" use a different style
" valid values: 'default' (default), 'darker', 'pure'
"let g:equinusocio_material_style = 'pure'

" Set shift width to 4 spaces.
set shiftwidth=4

" Set tab width to 4 whitespaces.
set softtabstop=4

" Use space characters instead of tabs.
set expandtab

set autoindent

" Do not wrap lines. Allow long lines to extend as far as the line goes.
set nowrap

" While searching though a file incrementally highlight matching characters as you type.
set incsearch

" Ignore capital letters during search.
set ignorecase

" Override the ignorecase option if searching for capital letters.
" This will allow you to search specifically for capital letters.
set smartcase

" Use highlighting when doing a search.
set hlsearch

" Send copied text to system clipboard
set clipboard=unnamed

set mouse=a

set number

set encoding=utf-8

if &rtp =~ 'plugged/vim-clang-format'
    let g:clang_format#detect_style_file = 1
    let g:clang_format#auto_format = 1
    " Uncomment the line below if using a virtual development workstation. An environment variable called MONGO_REPO has
    " to be defined for this to work. Additionally, $MONGO_REPO/build/clang-format has to be linked to the clang-format
    " binary.
    " let g:clang_format#command = $MONGO_REPO.'/build/clang-format'
endif

if &rtp =~'plugged/ale' && v:version >= 800
    let g:ale_linters_explicit = 1
    " Uncomment the lines below if using a virtual development workstation. An environment variable called MONGO_REPO
    " has to be defined for this to work.
    " let g:ale_linters = {'javascript' : ['eslint'] }
    " let g:ale_javascript_eslint_executable = $MONGO_REPO.'/build/eslint'
endif

if &rtp =~'plugged/vim-rtags'
    " Uncomment the lines below if using a virtual development workstation.
    " let g:rtagsAutoLaunchRdm = 1
endif
