call plug#begin()
Plug 'yunlingz/equinusocio-material.vim'
Plug 'rhysd/vim-clang-format'
call plug#end()

set termguicolors
colorscheme equinusocio_material

" use a different style
" valid values: 'default' (default), 'darker', 'pure'
"let g:equinusocio_material_style = 'pure'

" Set shift width to 4 spaces.
set shiftwidth=4

" Set tab width to 4 whitespaces.
set softtabstop=4

" Use space characters instead of tabs.
set expandtab

set autoindent

" Do not wrap lines. Allow long lines to extend as far as the line goes.
set nowrap

" While searching though a file incrementally highlight matching characters as you type.
set incsearch

" Ignore capital letters during search.
set ignorecase

" Override the ignorecase option if searching for capital letters.
" This will allow you to search specifically for capital letters.
set smartcase

" Use highlighting when doing a search.
set hlsearch

" Send copied text to system clipboard
set clipboard=unnamed

set mouse=a

set number

let g:clang_format#detect_style_file = 1
let g:clang_format#auto_format = 1
let g:clang_format#auto_format_on_insert_leave = 1
